// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateTask(ctx context.Context, arg CreateTaskParams) error
	DeleteTask(ctx context.Context, id string) error
	// query_tasks.sql
	FindTaskByID(ctx context.Context, id string) (Task, error)
	FindTasksByUserID(ctx context.Context, userID string) ([]Task, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	FindUserByID(ctx context.Context, id string) (User, error)
	GetLastInsertID(ctx context.Context) (int64, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) error
}

var _ Querier = (*Queries)(nil)
